export const ADD_DOG = 'ADD_DOG';
export const ADD_DOG_SUCCESS = 'ADD_DOG_SUCESS';
export const ADD_DOG_ERROR = 'ADD_DOG_ERROR';

export const LOADING_DOG = 'LOADING_DOG';
export const LOADING_DOG_SUCCESS = 'LOADING_DOG_SUCCESS';
export const LOADING_DOG_ERROR = 'LOADING_DOG_ERROR';

export const LOADING_TEMPERAMENT = 'LOADING_TEMPERAMENT';
export const LOADING_TEMPERAMENT_SUCCESS = 'LOADING_TEMPERAMENT_SUCCESS';
export const LOADING_TEMPERAMENT_ERROR = 'LOADING_TEMPERAMENT_ERROR';

export const GET_DOG_BY_NAME = 'GET_DOG_BY_NAME';
export const GET_DOG_BY_ID = 'GET_DOG_BY_ID';

